services:
  backend:
    image: ghcr.io/rekirky/things-ive-done-backend:latest
    container_name: tid-api
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/thingsivedonev:/app/data
    environment:
      - DB_PATH=/app/data/visits.db
    ports:
      - "6667:3000"

  frontend:
    image: ghcr.io/rekirky/things-ive-done-frontend:latest
    container_name: tid-ui
    restart: unless-stopped
    ports:
      - "6666:80"
    depends_on:
      - backend

  watchtower:
    image: containrrr/watchtower
    container_name: tid-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup tid-api tid-ui
