services:
  backend:
    image: ghcr.io/rekirky/things-ive-done-backend:latest
    container_name: tid-api
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=tid
    volumes:
      - /mnt/user/appdata/thingsivedonev:/app/data
    environment:
      - DB_PATH=/app/data/visits.db
      - SPOTIFY_CLIENT_ID=4f62139de8bf4e04856ac0072a93454f
      - SPOTIFY_CLIENT_SECRET=8558f2f1546446968d8d7e5c83fa734b
    ports:
      - "6801:3000"

  frontend:
    image: ghcr.io/rekirky/things-ive-done-frontend:latest
    container_name: tid-ui
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.scope=tid
    ports:
      - "6800:80"
    depends_on:
      - backend

  watchtower:
    image: containrrr/watchtower
    container_name: tid-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_SCOPE=tid
